language: node_js
node_js:
  - node
services: 
  - postgresql
before_script: 
  - psql -c 'CREATE DATABASE testpalettepicker;' -U postgres
  - knex migrate:latest --env=test
  - knex seed:run --env=test
notifications:
  email: false
deploy: 
  provider: heroku
  api_key: secure: GeVpcFDZf+hFTM6f8EcEoFYM7fQNWHwvwyZy6y5oYkuRsAu/l+HXrvzQo0l6PpxFrmx1Y1nJMNsR+EQTqW0W1G5NX3Gj2oyqfkbatr6Nhb2R7sPysV8gPt1aFcOJHbnbDdxat969AKIQXrJr0S8TEj1ug2vuWaVfd2ng0OHMUwRYJ2oKqIdA0WM/VMcm6LLXsmefiq20L4y7qZEsgsNIAp+qK92vOeP7OymC297QS9NUVXomLc2mlQUQovcFmQGyeWLEMMBsa87LE5PiRZD+yGAjZRT3wVn+lSBPbSFvczKTdOIZ+cf372FHgYnuby1WCkdDhZ/G8q5mvhMWtmg9sAwFF+MJasqk905cQSMRu4pLr1MKWvgCifdLUG40JwksQ8TFK7bZibqpgM+8wcx7UKgLZa4Ktp84V6vDIrac2TgYokN3RZx2y3POHSvD8sVBOS7KBXwitrxLCjm6we2iQEW/9U9uIT2nFJgZ8IvcEHi8wjtFKFwpmCBw0kJrrxyq1MhocQXup9VJX/NVFKaqX5TxBgPFFiLKnhUE4dDUQlCu1WbF/LrKzDX1flIkeFSczhGWhduiRM6tPNbkLPbaK6YddRSYplUJ+UawJaOMr+Lkqd/sVJLca6RvIkXM60kQvCarFcPMEW2KHQLyvTYOz1RPzas8oaG4GJEDZufuSWk=
app: travis-test-nyssas-rad-palette-picker
skip_cleanup: true

